const recipes = [
  {
    id: 1,
    name: 'Cheesy Slowcooker Lentils',
    description_short: 'These cheesy slow cooker lentils are almost zero effort to make, they’re tasty served in a million different ways, and you can use whatever veg you have on hand!',
    recipe_link: 'https://www.easycheesyvegetarian.com/cheesy-slow-cooker-lentils/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/12/Cheesy-slow-cooker-lentils-11.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '220',
    macros: {
      proteins: 37.6,
      carbs: 74.7,
      fats: 12.7,
      kcal: 553,
    },
  },
  {
    id: 2,
    name: 'Baked Bean Pizza',
    description_short: 'A homemade version of the classic Heinz baked bean pizza that was discontinued in the early 00s! Proper British kid nostalgia.',
    recipe_link: 'https://www.easycheesyvegetarian.com/baked-bean-pizza/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/09/Baked-bean-pizza-10.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '30',
    macros: {
      proteins: 33,
      carbs: 56.1,
      fats: 24.9,
      kcal: 611,
    },
  },
  {
    id: 3,
    name: 'Enchilada Lentil Casserole',
    description_short: 'This Tex-Mex lentil casserole is the perfect healthy comfort food – packed with veggies, and full of protein and fibre, but still cheesy and irresistible!',
    recipe_link: 'https://www.easycheesyvegetarian.com/enchilada-lentil-casserole/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/06/Enchilada-lentil-casserole-7.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '70',
    macros: {
      proteins: 42.5,
      carbs: 66.3,
      fats: 37.3,
      kcal: 767,
    },
  },
  {
    id: 4,
    name: 'Homemade Ricotta gnocchi',
    description_short: 'These homemade ricotta gnocchi are so light and fluffy, and much quicker and easier to make than potato gnocchi!',
    recipe_link: 'https://www.easycheesyvegetarian.com/homemade-ricotta-gnocchi/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2018/06/How-to-make-homemade-ricotta-gnocchi-10.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '45',
    macros: {
      proteins: 25.9,
      carbs: 36,
      fats: 24,
      kcal: 462,
    },
  },
  {
    id: 5,
    name: 'Warm Lentil Halloumi salad',
    description_short: 'This warm lentil and halloumi salad is great for eating at any time of year – plenty of yummy bits, and so filling!',
    recipe_link: 'https://www.easycheesyvegetarian.com/warm-lentil-halloumi-salad/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2012/07/Warm-lentil-and-halloumi-salad-6.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '25',
    macros: {
      proteins: 36.7,
      carbs: 34.6,
      fats: 32.4,
      kcal: 558,
    },
  },
  {
    id: 6,
    name: 'English Breakfast Burritos',
    description_short: 'These full English breakfast burritos are the ultimate weekend brunch – all the best bits of a vegetarian full English, wrapped up in a crispy tortilla!',
    recipe_link: 'https://www.easycheesyvegetarian.com/full-english-breakfast-burritos/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/05/Full-English-breakfast-burritos-11.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '40',
    macros: {
      proteins: 39.5,
      carbs: 36.7,
      fats: 34.4,
      kcal: 625,
    },
  },
  {
    id: 7,
    name: 'Lentil Halloumi Curry',
    description_short: 'This lentil and halloumi curry is really straightforward to make, and absolutely full of flavour – halloumi curry is a revelation!',
    recipe_link: 'https://www.easycheesyvegetarian.com/lentil-halloumi-curry/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2019/04/Easy-lentil-and-halloumi-curry-13.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '45',
    macros: {
      proteins: 27.5,
      carbs: 35.7,
      fats: 23.6,
      kcal: 451,
    },
  },
  {
    id: 8,
    name: 'Enchilada Noodles',
    description_short: 'These enchilada noodles are a quick and easy pasta dish with lots of flavour – perfect with plenty of Tex-Mex style toppings!',
    recipe_link: 'https://www.easycheesyvegetarian.com/enchilada-noodles/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2013/12/Enchilada-noodles-9.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '15',
    macros: {
      proteins: 26.1,
      carbs: 97.9,
      fats: 25.9,
      kcal: 725,
    },
  },
  {
    id: 9,
    name: 'Layered Tortillas',
    description_short: 'This layered tortilla hack has been going viral on TikTok, as it’s such an easy way to make a delicious lunch with any number of different fillings',
    recipe_link: 'https://www.easycheesyvegetarian.com/layered-tortillas/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2021/01/Layered-tortilla-hack-16.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '15',
    macros: {
      proteins: 31.5,
      carbs: 55.5,
      fats: 25.4,
      kcal: 594,
    },
  },
  {
    id: 10,
    name: 'Cheesy Lentil Pasta',
    description_short: 'This cheesy lentil pasta is the perfect hearty comfort food – made in just 20 minutes, with 6 store cupboard ingredients.',
    recipe_link: 'https://www.easycheesyvegetarian.com/cheesy-lentil-pasta/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/04/Cheesy-lentil-pasta-5.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '20',
    macros: {
      proteins: 35.7,
      carbs: 80.8,
      fats: 17.4,
      kcal: 625,
    },
  },
  {
    id: 11,
    name: 'Veggie Doner Kebab',
    description_short: 'A vegetarian doner kebab made with grilled halloumi, garlic mayonnaise and chips – the ultimate fake away!',
    recipe_link: 'https://www.easycheesyvegetarian.com/vegetarian-doner-kebab/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/02/Vegetarian-doner-kebab-12.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '35',
    macros: {
      proteins: 41.3,
      carbs: 72.8,
      fats: 37.8,
      kcal: 798,
    },
  },
  {
    id: 12,
    name: 'Crispy Tofu Escalopes',
    description_short: 'These tofu escalopes are breaded in a crispy, cheesy coating, and can be served in so many different ways. Perfect grown up vegetarian chicken nuggets!',
    recipe_link: 'https://www.easycheesyvegetarian.com/crispy-tofu-escalopes/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/10/Crispy-tofu-escalopes-7.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '45',
    macros: {
      proteins: 28.2,
      carbs: 28.7,
      fats: 27,
      kcal: 463,
    },
  },
  {
    id: 13,
    name: 'Vegan Katsu Curry',
    description_short: 'This vegan katsu curry is a tasty version of the popular Japanese dish, made with crispy breaded tofu and an aromatic curry sauce.',
    recipe_link: 'https://www.easycheesyvegetarian.com/vegan-katsu-curry/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/02/Vegan-katsu-curry-7.jpg',
    ingredients: [''],
    difficulty: 'Medium',
    time: '45',
    macros: {
      proteins: 32.9,
      carbs: 55.3,
      fats: 11.4,
      kcal: 402,
    },
  },
  {
    id: 14,
    name: 'Bean Halloumi Chilli',
    description_short: 'This black bean and halloumi chilli is so easy to make, and is packed with flavour, and little squidgy nuggets of halloumi cheese!',
    recipe_link: 'https://www.easycheesyvegetarian.com/black-bean-and-halloumi-chilli/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2020/04/Black-bean-and-halloumi-chilli-6.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '30',
    macros: {
      proteins: 26.1,
      carbs: 38.8,
      fats: 25.9,
      kcal: 473,
    },
  },
  {
    id: 15,
    name: 'Avocado Halloumi Wraps',
    description_short: 'These avocado and halloumi wraps are an incredibly tasty vegetarian lunch option – everything works so beautifully together!',
    recipe_link: 'https://www.easycheesyvegetarian.com/avocado-and-halloumi-wraps/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2019/04/Avocado-and-halloumi-wraps-5.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '10',
    macros: {
      proteins: 28.9,
      carbs: 42.8,
      fats: 41.9,
      kcal: 657,
    },
  },
  {
    id: 16,
    name: 'Creamy Garlic Mushroom Pasta',
    description_short: 'This creamy garlic mushroom tagliatelle is the perfect date night dinner – it can be on the table in 15 minutes, and the flavours are incredible!',
    recipe_link: 'https://www.easycheesyvegetarian.com/creamy-garlic-mushroom-tagliatelle/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2011/11/Creamy-garlic-mushroom-tagliatelle-4.jpg',
    ingredients: [''],
    difficulty: 'Easy',
    time: '15',
    macros: {
      proteins: 27.2,
      carbs: 68.7,
      fats: 26.4,
      kcal: 612,
    },
  },
  {
    id: 17,
    name: 'Enchilada Stuffed Pasta Shells',
    description_short: 'Giant pasta shells stuffed with a creamy, enchilada-inspired filling, and covered in homemade enchilada sauce – the perfect fusion.',
    recipe_link: 'https://www.easycheesyvegetarian.com/enchilada-stuffed-pasta-shells/',
    image_link: 'https://www.easycheesyvegetarian.com/wp-content/uploads/2012/09/Enchilada-stuffed-pasta-shells-12.jpg',
    ingredients: [''],
    difficulty: 'Hard',
    time: '70',
    macros: {
      proteins: 29.5,
      carbs: 61.8,
      fats: 23.9,
      kcal: 572,
    },
  },
];

export default recipes;
